### ISSUE TITLE
Dashboard Improvements

### ISSUE THREAD

**Issue by MaikNeubert** [boxwise/boxtribute#1082]
- clarify meaning of viz 
  - if neccessary modify titles of viz (i.e. Created Boxes)
  - legends
  - axis description
- Sankey: 
  - also show percentage 
  - “Can we order the flows from biggest to smallest? What about alphabetically?”
  - “Can we feed in some custom coloring based on our own parameters (e.g., this is to Greece, this is to Serbia, this is to France, etc.)”
  - what shipping state is depicted on the far right? 'sent'/'receiving'/'completed'? Clarify on axis 
(- Sunburst (after filtering improvements):
  - if neccessary set default to 'show only the inner two rings'
    - if possible make it customizable )

**Comment by MaikNeubert** [comment]
@seinig @boxwise/admin 
I created this issue to collect further UI/UX improvements that need to be made for the dashboard.
If you have any requirements for the dashboard (except the publishing and export) you can write it down here

**Comment by seinig** [comment]
I collected the points above from some protocols and from @aerinsol 's [List](https://docs.google.com/document/d/1Zq9tTFj5XxrQhzI53Wb395anfm5or21PS--SxpsYssA/edit). In the linked document i highlighted those aspects that still seem relevant to me. I added those which are still open to the list above. In some cases I'm not sure whether issues from the linked list are already done and implemented, so you might also have a look, @MaikNeubert . There certainly are quite a few aspects out of scope, so we surely can focus on the most important stuff.

**Comment by aerinsol** [comment]
Other thoughts - I do have a clear idea in mind on how the charts should render in mobile viewports. Let me know if you need help there @MaikNeubert since it will be likely easier for me to talk you through it rather than for you to read a long list of requirements.

**Comment by seinig** [comment]
Specific feedback from HERMINEs com department

Top Products
- wording seems off - we act demand-orientated, i.e. there is no 'top/leading product'

Sankey
- Axis designations would be helpful
- what is the difference between self reported & shipments?
- self reported does not sound trustworthy

Donut
- Some kind of manual how to use this interactive chart would be good, looks overwhelming on first sight

**Comment by aerinsol** [comment]
I'm consolidating the above list from Valentin with other feedback, please
don't prioritize this yet Maik.
