### ISSUE TITLE
Statviz 1st live test Bugs/Improvements

### ISSUE THREAD

**Issue by MaikNeubert** [boxwise/boxtribute#1221]

**Comment by MaikNeubert** [comment]
* Data Picker doesn't get updated if the same day on another month/year is picked
* Moved Boxes is not updating when Timerange is updated

**Comment by aerinsol** [comment]
From Seb of GW

> But one last thing.. is it possible to see the moved items and not only the moved boxes? 
> 
> And a summary of the generated new items per year and not only the monthly statistics? 

I believe the moved items was already done @MaikNeubert

**Comment by MaikNeubert** [comment]
@aerinsol @seinig 
Update from the Tech-Standup with @aerinsol and @MaikNeubert 

* Info icon next to filters
* Text in stock overview that it is not affected by products gender and products filter

* Shipments graph
    * negative values as red (!!)
    * if there is only one type of shipments (e. g. selfreported) collapes outgoing boxes

* created Boxes
    * reveres display by grouping -> year, month, week, day

* Downloads aren't working sometimes
    * try to download SVG -> Spinning forever
* PNG downloads a black image
