### ISSUE TITLE
2nd iteration bugfixes/improvements

### ISSUE THREAD

**Issue by MaikNeubert** [boxwise/boxtribute#1275]
## Feature Refinements Needed Before Launch for Basic Usability
Beneficiary Title should be "Beneficiaries Registered"

- [x]  Top Products Title should be "Top Created Products"
- [x] Sankey - exclude all orange and red-tinted colors from positive flows

~~Sankey - negative flows should have a negative number and be in the format "<locationname> (incoming)", e.g. "Stockroom (incoming) -40"~~ -> currently not possible

- [x] Sankey - "Negative Box Flow" Legend at the bottom of the graph should instead say "Red targets indicate an incoming/reverse flow, i.e. a removal of items/boxes from that location to instock storage."
- [x] Sankey - outgoing boxes should be renamed EITHER "outgoing <boxes/items>" or "outgoing stock"

-  [x] Sankey - Shipment flows should include the orgname, so <basename> | <orgname> e.g. " Samos | Samos Volunteers", "Lakadikia | IHA" -> @pylipp is it possible to add this to the target dimension of the moved boxes query?
Probably next iteration -> update already merged to master

- [x] Stock Chart - Rename it to "Drilldown Chart of Instock Items/Boxes"
- [x] Stock Chart-  Change the grouping Control Name to "Grouped by", and the text next to it to "Current Grouping: <Group>" instead of the current "<Group>"
- [x] Add Text in the Donut Center that summarizes the current drilldown level and split (e.g., "All Items by Category", "Tops by Size", "Women's Items/Boxes by Category" "S Sizes by Product") - this should be visible in the download.
- [x] Beneficiary title: "Beneficiaries Registered"

## Small Feature Refinements for Better Impact
- [ ] Tag, Gender, and Product Gender filters should be viewable in the Graph Title ("filtered by..." between viz title and download options)
- [ ] Sankey - default order flows by size, largest to smallest
- [x] make filter panel sticky
- [ ] include applied filters in downloads as an option

## Larger Feature Refinements for Better Impact
- [ ] Thousand Separator Radio Control (None | Comma | Period)
- [ ] Sorting Control for Sankey (biggest -> smallest, Smallest -> Biggest, A->Z, Z->A)

**Comment by pylipp** [comment]
Hej @MaikNeubert adding org dimension should be easy. Is the organisation name as single field alright, or do you want the organisation ID in the facts and then look up the name in the dimensions info?

**Comment by MaikNeubert** [comment]
@pylipp 
organisation name as single field in the target dimension would be best, keep it simple :)

**Comment by pylipp** [comment]
@MaikNeubert is it okay if the org name is only present for `Shipment` type movements?

It does not make much sense for the `BoxState` or `OutgoingLocation` types since the only related organisation is the one of the user. For these types `null` will be returned.

**Comment by MaikNeubert** [comment]
@pylipp yes, that would be ok

**Comment by pylipp** [comment]
https://github.com/boxwise/boxtribute/pull/1282
