### ISSUE TITLE
[2nd viz]: Data structure for visualization exploration: Is it possible to show the flow of inventory from one place to another over time?

### ISSUE THREAD

**Issue by pylipp** [boxwise/boxtribute#878]
Requirements: 

1. It must be possible to customize the start and end date of the period displaying flows.
2. It must be possible to filter the flow of inventory by one or more product types.
3. It must be possible to filter the flow of inventory by category type.
4. "Place" can be defined as a warehouse location or transfer source/destination.

Stretch goal:
Do a similar exploration but with `box_state.`

**Comment by pylipp** [comment]
Main goal: show the flow of inventory from one place to another over time
## Status quo
- Changes to boxes (product, location, size, nr of items, state) are being tracked in the history table
- Given a source location S and a time range T, the following query returns a list of all boxes that have been moved to target locations (optionally filtered by products P)
```
SELECT changedate,
record_id AS box_id,
from_int AS source_location_id,
to_int AS target_location_id /* ,b.product_id, b.items */
FROM history 
/* JOIN stock AS b ON b.id = box_id */
WHERE tablename = "stock" 
AND changedate > T 
AND changes = "location_id" 
AND from_int = S
/* AND b.product_id in P */ ;
```

- With this, requirements 1, 2, and 4 are met. Requirement 3 can be fulfilled by either joining with the products table, and filtering by category; or by passing all products of a category as P
- The resulting data rows will be returned as JSON; either as “single block” or using GraphQL resolvers to adjust to the fields required by the FE
- The performance of the request and the size of the response depends on the query parameters, mostly on the time range T
## Caveat
Joining with the stock table to find product and box items brings in the current properties of the box which might not necessarily match the properties in the requested time period.

**Comment by pylipp** [comment]
! WIP !
## Outlook: shadow tables
It was [proposed](https://github.com/boxwise/boxtribute/blob/master/docs/adr/adr_database-history.md) earlier to introduce shadow tables to the boxtribute database schema to enable more accurate tracking of historical data (mostly stock; also product, beneficiaries, products, locations, tags, qr).
It shall be explored how the requested data can be fetched in such a scenario.
- For recap: the stock shadow table contains the same columns, and an effective_from column
- Given a source location S and a time range T1-T2 (old-new), the following query returns a list of all boxes that have been moved to target locations (optionally filtered by products P)
    - obtain stock at beginning of time range T1 and end of time range T2
```
SELECT * from shadow_stock
WHERE effective_from = ( SELECT MAX(effective_from) FROM shadow_stock WHERE effective_from < T1 );
SELECT * from shadow_stock
WHERE effective_from = ( SELECT MAX(effective_from) FROM shadow_stock WHERE effective_from < T2 );
```

**Comment by pylipp** [comment]
## Another user story
Can we use the current data structure of the history table for the following case: 
Show me where boxes were moved, incl. their product and number of items, by a certain date D
of boxes that were created in my warehouse in a certain timespan T

### Data format of result
Dimensions:
- product ID
- "target"
    - location ID + InStock/Donated (box was moved within my base)
    - state Lost (box was marked as lost in my base)
    - state Scrap (box was marked as scrap in my base)
    - MarkedForShipment + target base (box is about to be shipped to target)
    - InTransit + target base (box is being shipped to target)
    - location ID + InStock/Donated + target base (box was shipped to target; and then moved within that base)
    - Other (box is still in my base but product or number of items changed)

### Implementation
We expect that a basic SQL query could look like

```sql
SELECT h.*, s.id FROM history h
INNER JOIN stock s ON (h.tablename = "stock" AND h.record_id = s.id)
WHERE h.id IN (
    SELECT id FROM history WHERE change_date WITHIN T AND changes = "Record created" AND tablename = "stock"
) GROUP BY s.id;
```
This results in a mapping of box IDs and history rows (i.e. changes). For each box ID we find out the change that has happened closest before D _and_ is that is a location, product, or state change. Any potential changes that happened after D must be taken into account (possible change of items or change of product) in order to determine the properties of the box at D.

**Comment by HaGuesto** [comment]
please checkout #950 for final decision
