### ISSUE TITLE
Research data preparation in backend for first user story

### ISSUE THREAD

**Issue by pylipp** [boxwise/boxtribute#888]
## user story

I, as a warehouse coordinator, want to see how many boxes and items I have moved from a warehouse location to a donated location like a free shop in a time range, possibly filterable by product, size, gender. The diagram should be a bar plot where each bar represents a customizable time period.

## Task description
@pylipp figure out what we would have to do to prepare the data and pass it to the frontend.
Please start a doc where we collect the additional queries we have to create for the visualizations with their requirements, variables, user stories, and the data structure that is returned.

Please consider at least two options: write the query in the current data-structure and in the perfect data structure for the query.
What would be the trade-offs in performance, cost and implementing the data structure/query

Update 2023-07-24: list of boxes grouped by location for one product in a given time range
Update August 2023: first user story shall be about beneficiary demographics.

**Comment by pylipp** [comment]
## User story: beneficiary demographics

We'd like to obtain the number of beneficiaries (fact) for all sets of gender, age(-bin), and creation date (dimensions).

### BE implementation

Such data can be obtained by first querying beneficiary rows, then transforming it into a pivot table (e.g. using the pandas framework; `id` as values, `gender, created_on, age` as index, `count` as aggfunc), and finally transforming this table into single data points again.

However due to the simplicity of the aggregation, the data can be obtained directly from the DB via 

```python
    bin_width = 5
    gender = fn.IF(Beneficiary.gender == "", "D", Beneficiary.gender)
    created_on = db.database.truncate_date("day", Beneficiary.created_on)
    age = fn.FLOOR((date.today().year - Beneficiary.date_of_birth.year) / bin_width)

    demographics = (
        Beneficiary.select(
            gender.alias("gender"),
            created_on.alias("created_on"),
            age.alias("age"),
            fn.COUNT(Beneficiary.id).alias("count"),
        )
        .where(Beneficiary.deleted.is_null())  # add base IDs
        .group_by(SQL("gender"), SQL("age"), SQL("created_on"))
    )
```

### Data format

The resulting data format is a list of objects with keys `age`, `gender`, `created_at`, and `count`.

### GraphQL interface

To return the data via GraphQL the following extension is proposed:

```graphql
type Metrics {
  ...
  beneficiaryDemographics(baseIds: [Int]): [BeneficiaryDemographicsResult]
}

type BeneficiaryDemographicsResult {
  age: Int
  gender: HumanGender
  createdOn: Datetime
  count: Int
}
```

**Comment by HaGuesto** [comment]
works from my side
