### ISSUE TITLE
Talk to Hermine teams for user stories

### ISSUE THREAD

**Issue by seinig** [boxwise/boxtribute#897]

**Comment by HaGuesto** [comment]
The result of the Hermine internal user research can be found here:
https://docs.google.com/spreadsheets/d/1BGRHsgQsOMS8QahhsivA7yB_ayR9TJiGn5AJF2uJgX0/edit?usp=sharing
https://docs.google.com/document/d/1bZQyHNYDCgPZtZZj-5bD0kCQlFLMhWYvnIBcAIzdaWQ/edit?usp=sharing

**Comment by HaGuesto** [comment]
closed and moved to slack canvas
