### ISSUE TITLE
[2nd viz] BE public graphQL query: statistics about created boxes

### ISSUE THREAD

**Issue by seinig** [boxwise/boxtribute#898]
Boxes (and contained items) generated in a base within certain time, filterable by product, category.

parameter: base

facts: number of boxes and number of items
 
1. fact table
(cat_id)
prod_id
createdOn
gender_name
#boxes
#items

2. dim-category
cat_id
cat_name

3. dim-products
prod_id
prod_name

## Data format

```json
{
  "facts": [
    {"categoryId": 1, "productId": 1, "createdOn": "2022-08-22", "gender": "Male", "boxesCount": 3, "itemsCount": 44},
    ...
  ],
  "dimensions": {
    "product": [
      {"id": 1, "name": "T-Shirts"},
      ...
    ],
    "category": [
      {"id": 1, "name": "Clothing"},
      ...
    ]
  }
}
```

## GraphQL query example
```graphql
query { createdBoxes {
        facts {
            createdOn categoryId productId gender boxesCount itemsCount
        }
        dimensions {
            product { id name }
            category { id name }
    } } }
```

**Comment by pylipp** [comment]
@MaikNeubert @HaGuesto FYI data format is defined above
