### ISSUE TITLE
[2nd viz] Exploration: reconstruct box properties from history

### ISSUE THREAD

**Issue by pylipp** [boxwise/boxtribute#918]

**Comment by pylipp** [comment]
@seinig yes, this issue belongs to that milestone, rather than to 2nd viz. I'm renaming it because it's not the final implementation.

**Comment by seinig** [comment]
@pylipp alright, perfect! I added the first issue to the new milestone concerning the script. Please feel free to add/edit them.

**Comment by pylipp** [comment]
Exploration is done. This ticket is superseded by #947
