### ISSUE TITLE
[2nd viz] FE create / adapt viz component

### ISSUE THREAD

**Issue by seinig** [boxwise/boxtribute#924]

**Comment by seinig** [comment]
@MaikNeubert I just wanted to check in wether you think it's realistic to finish a first version of the 2nd viz this week, or when will you be able to work on it?

**Comment by aerinsol** [comment]
@MaikNeubert Hey, I just realized that the FE requirements here could be better. I have some ideas, but I'd like to make sure they're aligned with where you are. 

What style of visualization were you thinking of doing here? A bar chart or a donut chart? With beneficiary data or inventory data? 

To be clear, on my end, my idea of what was happening FE viz was: 
1. The population chart, with filters
2. Created Boxes/items, as EITHER a bar chart by day or as a pie/donut chart for a period

If that's not aligned with what you had in mind let me know.

**Comment by MaikNeubert** [comment]
Hi, for me i understood it the following way
2. bar chart (currently working on)
3. Pie chart
4. maybe sankey?

**Comment by MaikNeubert** [comment]
@aerinsol 

![Image](https://github.com/boxwise/boxtribute/assets/47301268/1b793803-9c7c-46ce-a358-64f82c53434d)

**Comment by aerinsol** [comment]
Wonderful!! I think this already can fulfill the DSEE100x requirement of
increasing civic engagement and volunteering with HERMINE volunteer teams.

**Comment by aerinsol** [comment]
@MaikNeubert , based on my most recent conversation with @seinig , we may not end up using the bar chart. Being able to do the pie chart will be important though. 

Also quick question on the above. Is using days on the X-axis fixed, or is it possible to group by, say, month or week? (not a request, just a clarification).

**Comment by MaikNeubert** [comment]
@aerinsol 
Currently it is fixed to be grouped by day.
I suggested we invest some work in the future to provide flexible grouping here with the options to group per day, week and month, Depending on the Size of an organisation they create boxes almost every day, once or twice a week or a few times per month.
