### ISSUE TITLE
[C / 2nd viz] FE add interactions (e.g. filters) to viz

### ISSUE THREAD

**Issue by seinig** [boxwise/boxtribute#926]

**Comment by seinig** [comment]
currently the only filter request for the 2nd viz is time range.
A screenshot/look at the visualized data might be helpful in order to determine, which kind of filters we could add. 
Maybe product category might be an intresting filters here. 

Not sure if 'filter', but possibility to change grouping settings for x-axis between by day/week/month could be intresting to some. I think you picked week as default which is totally fine and i don't see a priority here

**Comment by MaikNeubert** [comment]
Filters and Interactions are added in the Dashbaord+ux PR
