### ISSUE TITLE
Design: How the sharing (embedding) of visualizations should work 

### ISSUE THREAD

**Issue by seinig** [boxwise/boxtribute#927]
- How should a user copy the url and filters to embed via an iframe into a webpage or newsletter?
- What options should there be for exporting?
- Should we give them different fixed size options?
- should there be a share button?
- should the filter be extra or in the visualizations?

**Comment by aerinsol** [comment]
We are working on this. Noted that export is higher value than embed from all interviewed partners including HERMINE.

**Comment by seinig** [comment]
We came to an conclusion on the strategy, see [this ticket](https://github.com/boxwise/boxtribute/issues/1093)
